# Generated by Django 4.0.3 on 2022-05-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_filme_atores_filmelinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('A', 'Ação'), ('R', 'Romance'), ('F', 'Ficção'), ('T', 'Terror')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
