# Generated by Django 4.0.3 on 2022-05-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_alter_filme_categoria_delete_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('acao', 'Ação'), ('romance', 'Romance'), ('ficcao', 'Ficção'), ('terror', 'Terror'), ('aventura', 'Aventura'), ('suspense', 'Suspense'), ('anime', 'Anime')], max_length=9),
        ),
        migrations.AlterField(
            model_name='filme',
            name='status',
            field=models.CharField(choices=[('RA', 'Recem Adicionado'), ('MA', 'Mais Assistidos'), ('TR', 'Top Rated')], max_length=9),
        ),
    ]
