# Generated by Django 4.0.3 on 2022-05-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0007_filme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='filme_trailer',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
