# Generated by Django 4.0.3 on 2022-05-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0009_filme_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='banner',
            field=models.ImageField(default='', upload_to='filmes_banner'),
            preserve_default=False,
        ),
    ]
